### PR TITLE
Remove obsolete encode_from_qstring function

### PR DESCRIPTION
**Pull request by wolny**

### CODE REVIEW

**Review by k-dominik — COMMENTED** [review]
this file has not been ported to PyQt5, so better to leave it in place. Need to check whether this is needed at all, anymore.

**Comment by wolny** [comment]
nice catch! I could try to port it to PyQt5 then, or feel free to close this PR otherwise.

**Comment by stuarteberg** [comment]
This whole repo needs to be ported to Qt5, if anyone plans on using it.  But I suspect the most expedient thing to do is to just remove mentions of this repo from ilastik.

Relevant files:

```
$ cd ilastik-meta/ilastik
$ git grep -l eventcapture
.gitmodules
ilastik/shell/gui/ilastikShell.py
ilastik/shell/gui/startShellGui.py
ilastik_main.py
```

**Comment by wolny** [comment]
I agree that removing the `eventcapture` dependency from `ilastik` would be the course of action. `ilastik` doesn't use PyQt4 anymore anyway, so the `eventcaputre` *should* be removed from there

**Pull request closed without merging**
